/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   index.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {OAuth2Authorization} from './src/OAuth2Authorization.js';

export {OAuth1Authorization} from './src/OAuth1Authorization.js';
