/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   oauth2-authorization.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />

/**
 * The `<outh2-authorization>` performs an OAuth2 requests to get a token for given settings.
 *
 * There are 4 basic token requests flows:
 * - Authorization Code for apps running on a web server (`authorization_code` type)
 * - Implicit for browser-based or mobile apps (`implicit` type)
 * - Password for logging in with a username and password (`password` type)
 * - Client credentials for application access (`client_credentials` type)
 *
 * This element uses them all.
 *
 * Main function is the `authorize()` function that can be also used via event system.
 * This function accepts different set of parameters depending on request type. However it will
 * not perform a validation on the settings. It will try to perform the request for given set of
 * parameters. If it fails, than it fail on the server side.
 *
 * ### Example
 *
 * ```
 * <outh2-authorization></outh2-authorization>
 * ```
 * ```
 * const settings = {
 *   type: 'implicit',
 *   clientId: 'CLIENT ID',
 *   redirectUrl: 'https://example.com/auth-popup.html',
 *   authorizationUrl: 'https://auth.example.com/token'
 *   scopes: ['email'],
 *   state: 'Optional string'
 * };
 * const factory = document.querySelector('outh2-authorization');
 * factory.authorize(settings)
 *
 * // or event based
 * const event = new CustomEvent('oauth2-token-requested', { 'detail': settings, bubbles: true });
 * document.dispatchEvent(event);
 * ```
 *
 * There is one difference for from using event based approach. When the token has been received
 * this will set `tokenValue` property on the target of the event.
 * The event will be canceled one it reach this element so other elements will not double the action.
 *
 * An element or app that requesting the token should observe the `oauth2-token-response` and
 * `oauth2-error` events to get back the response.
 *
 * ## Popup in authorization flow
 *
 * This element conatin a `oauth-popup.html` that can be used to exchange token / code data with
 * hosting page. Other page can be used as well. But in must `window.postMessage` back to the
 * `window.opener`. The structure of the message if the parsed query or has string to the map
 * of parameters. Furthermore it must camel case the parameters. Example script is source code
 * of the `oauth-popup.html` page.
 * Popup should be served over the SSL.
 *
 * ## The state parameter and security
 *
 * This element is intened to be used in debug applications where confidentialy is already
 * compromised because users may be asked to provide client secret parameter (depending on the flow).
 * *It should not be used in client applications** that don't serve debugging purposes.
 * Client secret should never be used on the client side.
 *
 * To have at least minimum of protection (in already compromised environment) this library generates
 * a `state` parameter as a series of alphanumeric characters and append them to the request.
 * It is expected to return the same string in the response (as defined in rfc6749). Though this
 * parameter is optional, it will reject the response if the `state` parameter is not the same as the
 * one generated before the request.
 *
 * The state parameter is generated automatically by the element if non provided in
 * settings. It is a good idea to use this property to check if the event response
 * (either token or error) are comming from your request for token. The app can
 * support different oauth clients so you can check later with the token response if
 * this is a response for the same client.
 *
 * ## Non-interactive authorization (experimental)
 *
 * For `implicit` and `code` token requests you can set `interactive` property
 * of the settings object to `false` to request the token in the background without
 * displaying any UI related to authorization to the user.
 * It can be used to request an access token after the user authorized the application.
 * Server should return the token which will be passed back to the application.
 *
 * When using `interactive = false` mode then the response event is always
 * `oauth2-token-response`, even when there was authorization error or user never
 * authorized the application. In this case the response object will not carry
 * `accessToken` property and always have `interactive` set to `false` and `code`
 * to determine cause of unsuccesful request.
 *
 * ### Example
 *
 * ```
 * const settings = {
 *   interactive: false,
 *   type: 'implicit',
 *   clientId: 'CLIENT ID',
 *   redirectUrl: 'https://example.com/auth-popup.html',
 *   authorizationUrl: 'https://auth.example.com/token'
 *   state: '1234'
 * };
 * const event = new CustomEvent('oauth2-token-requested', { 'detail': settings, bubbles: true });
 * document.dispatchEvent(event);
 *
 * document.body.addEventListener('oauth2-token-response', (e) => {
 *   let info = e.detail;
 *   if (info.state !== '1234') {
 *     return;
 *   }
 *   if (info.interactive === false && info.code) {
 *     // unsuccesful request
 *     return;
 *   }
 *   let token = info.accessToken;
 * });
 * ```
 *
 * ## Demo
 * See `auth-methods` > `auth-method-oauth2` element for the demo.
 */
declare class OAuth2Authorization extends Polymer.Element {

  /**
   * A full data returned by the authorization endpoint.
   */
  readonly tokenInfo: object|null|undefined;
  connectedCallback(): void;
  disconnectedCallback(): void;
  clear(): void;

  /**
   * Clean up popup reference and closes the window if not yet closed.
   */
  _cleanupPopup(): void;

  /**
   * Handler for the `oauth2-token-requested` custom event.
   */
  _tokenRequestedHandler(e: CustomEvent|null): void;

  /**
   * Authorize the user using provided settings.
   * See `auth-methods/auth-method-oauth2` element for more information about settings.
   */
  authorize(settings: any): void;

  /**
   * Authorizes the user in the OAuth authorization endpoint.
   * By default it authorizes the user using a popup that displays
   * authorization screen. When `interactive` property is set to `false`
   * on the `settings` object then it will quietly create an iframe
   * and try to receive the token.
   *
   * @param authUrl Complete authorization url
   * @param settings Passed user settings
   */
  _authorize(authUrl: String|null, settings: object|null): void;

  /**
   * Creates and opens auth popup.
   */
  _authorizePopup(url: any): void;

  /**
   * Tries to Authorize the user in a non interactive way.
   * This method always result in a success response. When there's an error or
   * user is not logged in then the response won't contain auth token info.
   */
  _authorizeTokenNonInteractive(url: any): void;

  /**
   * Removes the frame and any event listeners attached to it.
   */
  _cleanupFrame(): void;

  /**
   * Handler for `error` event dispatched by oauth iframe.
   */
  _frameLoadErrorHandler(): void;

  /**
   * Handler for iframe `load` event.
   */
  _frameLoadHandler(): void;

  /**
   * Observer if the popup has been closed befor the data has been received.
   */
  _observePopupState(): void;

  /**
   * Browser or server flow: open the initial popup.
   *
   * @param settings Settings passed to the authorize function.
   * @param type `token` or `code`
   * @returns Full URL for the endpoint.
   */
  _constructPopupUrl(settings: object|null, type: String|null): String|null;

  /**
   * Applies custom properties defined in the OAuth settings object to the URL.
   *
   * @param url Generated URL for an endpoint.
   * @param data `customData.[type]` property from the settings object.
   * The type is either `auth` or `token`.
   */
  _applyCustomSettingsQuery(url: String|null, data: object|null): String|null;

  /**
   * Computes `scope` URL parameter from scopes array.
   *
   * @param scopes List of scopes to use with the request.
   * @returns Computed scope value.
   */
  _computeScope(scopes: Array<String|null>|null): String|null;

  /**
   * Listen for a message from the popup.
   *
   * Token will be extracted and `oauth2-token-response` will be fired. Also, if the initial
   * request came from an event, a `tokenValue` property fill be set on the event target.
   */
  _popupMessageHandler(e: any): void;

  /**
   * http://stackoverflow.com/a/10727155/1127848
   */
  randomString(len: any): any;
  _beforePopupUnloadHandler(): void;

  /**
   * Exchange code for token.
   * One note here. This element is intened to use with applications that test endpoints.
   * It asks user to provide `client_secret` parameter and it is not a security concern to him.
   * However, this method **can't be used in regular web applications** because it is a
   * security risk and whole OAuth token exchange can be compromised. Secrets should never be
   * present on client side.
   *
   * @param code Returned code from the authorization endpoint.
   */
  _exchangeCode(code: String|null): void;

  /**
   * Returns a body value for the code exchange request.
   *
   * @param settings Initial settings object.
   * @param code Authorization code value returned by the authorization
   * server.
   * @returns Request body.
   */
  _getCodeEchangeBody(settings: object|null, code: String|null): String|null;

  /**
   * Applies custom body properties from the settings to the body value.
   *
   * @param body Already computed body for OAuth request. Custom
   * properties are appended at the end of OAuth string.
   * @param data Value of settings' `customData` property
   * @returns Request body
   */
  _applyCustomSettingsBody(body: String|null, data: object|null): String|null;
  _tokenCodeRequest(url: any, body: any): void;

  /**
   * Decode token information from the response body.
   */
  _handleTokenCodeResponse(data: any, contentType: any): void;

  /**
   * Handler fore an error that happened during code exchange.
   */
  _handleTokenCodeError(e: Error|null): void;

  /**
   * Replaces `-` or `_` with camel case.
   *
   * @param name The string to process
   * @returns Camel cased string or `undefined` if not
   * transformed.
   */
  _camel(name: String|null): String|null|undefined;

  /**
   * Requests a token for `password` request type.
   *
   * @param settings Settings passed to the `authorize()` function.
   */
  _authorizePassword(settings: object|null): void;

  /**
   * Generates a payload message for password authorization.
   *
   * @param settings Settings object passed to the `authorize()`
   * function
   * @returns Message body as defined in OAuth2 spec.
   */
  _getPasswordBody(settings: object|null): String|null;

  /**
   * Requests a token for `client_credentials` request type.
   *
   * @param settings Settings passed to the `authorize()` function.
   */
  _authorizeClientCredential(settings: object|null): void;

  /**
   * Generates a payload message for client credentials.
   *
   * @param settings Settings object passed to the `authorize()`
   * function
   * @returns Message body as defined in OAuth2 spec.
   */
  _getClientCredentialBody(settings: object|null): String|null;

  /**
   * Applies custom headers from the settings object
   *
   * @param xhr Instance of the request object.
   * @param data Value of settings' `customData` property
   */
  _applyCustomSettingsHeaders(xhr: XMLHttpRequest|null, data: object|null): void;

  /**
   * Dispatches an error event that propagates through the DOM.
   *
   * @param detail The detail object.
   */
  _dispatchError(detail: object|null): void;

  /**
   * Dispatches an error event that propagates through the DOM.
   *
   * @param detail The detail object.
   */
  _dispatchResponse(detail: object|null): void;
}

interface HTMLElementTagNameMap {
  "oauth2-authorization": OAuth2Authorization;
}
