/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   outh-authorization.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {OAuth1Authorization} from './oauth1-authorization.js';

export {OAuth2Authorization} from './oauth2-authorization.js';
